/**
 * GraphQL Code Generator Configuration
 *
 * Generates TypeScript types and React Apollo hooks from the backend GraphQL API.
 * Run with: pnpm codegen
 *
 * Requirements:
 * - Backend API must be running at http://localhost:4000/graphql
 */

import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  // Introspect from the running backend API
  schema: 'http://localhost:4000/graphql',

  // Look for GraphQL operations in .graphql files
  documents: ['src/graphql/**/*.graphql'],

  // Generate output
  generates: {
    // Generated types and hooks
    'src/generated/graphql.ts': {
      plugins: [
        {
          add: {
            content: '/* eslint-disable */\n// @ts-nocheck\n// This file is auto-generated by GraphQL Code Generator. Do not edit.',
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-react-apollo',
      ],
      config: {
        // Use proper TypeScript types
        strictScalars: true,
        scalars: {
          Decimal: 'string',
          DateTime: 'string',
          ID: 'string',
        },
        // Generate React hooks
        withHooks: true,
        withHOC: false,
        withComponent: false,
        // Better naming
        dedupeFragments: true,
        // Export types
        enumsAsTypes: true,
        // Avoid conflicts
        skipTypename: false,
        // Apollo Client 4 compatibility
        apolloClientVersion: 4,
        apolloReactHooksImportFrom: '@apollo/client/react',
        // Use graphql-tag instead of DocumentNode (fixes import issue)
        documentMode: 'graphQLTag',
        gqlImport: '@apollo/client#gql',
      },
    },
  },

  // Ignore files in generated folder
  ignoreNoDocuments: true,
};

export default config;

